#lang racket

; Allows for the creation of a hash table to store the stations, their neighbors 
; and the time to travel to the next station
(define (make-mutable-graph)
  (make-hash '()))

; Adds the edge (connection between stations) to the vertexes (stations)
(define (add-edge! line station1 time)
  (define new-edges (cons (list station1 time) (hash-ref line 'edges '())))
  (hash-set! line 'edges new-edges))

; Northern Line
(define northern-line (make-mutable-graph))
(add-edge! northern-line "high barnet" 4)
(add-edge! northern-line "totteridge & whetstone" 2)
(add-edge! northern-line "woodside park" 2)
(add-edge! northern-line "west finchley" 2)
(add-edge! northern-line "finchley central" 3)
(add-edge! northern-line "east finchley" 2)
(add-edge! northern-line "highgate" 3)
(add-edge! northern-line "archway" 2)
(add-edge! northern-line "tufnell park" 2)
(add-edge! northern-line "kentish town" 2)
(add-edge! northern-line "camden town" 2)
(add-edge! northern-line "chalk farm" 2)
(add-edge! northern-line "belsize park" 2)
(add-edge! northern-line "hampstead" 4)
(add-edge! northern-line "golders green" 3)
(add-edge! northern-line "brent cross" 2)
(add-edge! northern-line "hendon central" 3)
(add-edge! northern-line "colindale" 2)
(add-edge! northern-line "burnt oak" 3)
(add-edge! northern-line "camden town to mornington crescent" 2)
(add-edge! northern-line "mornington crescent" 1)
(add-edge! northern-line "euston to kings cross st pancras" 2)
(add-edge! northern-line "kings cross st pancras" 2)
(add-edge! northern-line "angel" 3)
(add-edge! northern-line "old street" 2)
(add-edge! northern-line "moorgate" 2)
(add-edge! northern-line "bank" 2)
(add-edge! northern-line "london bridge" 1)
(add-edge! northern-line "borough" 2)
(add-edge! northern-line "elephant & castle" 2)
(add-edge! northern-line "euston to warren street" 1)
(add-edge! northern-line "warren street" 2)
(add-edge! northern-line "goodge street" 1)
(add-edge! northern-line "tottenham court road" 1)
(add-edge! northern-line "leicester square" 2)
(add-edge! northern-line "charing cross" 1)
(add-edge! northern-line "embankment" 2)
(add-edge! northern-line "waterloo" 3)
(add-edge! northern-line "kennington" 2)
(add-edge! northern-line "oval" 2)
(add-edge! northern-line "stockwell" 2)
(add-edge! northern-line "clapham north" 1)
(add-edge! northern-line "clapham common" 2)
(add-edge! northern-line "clapham south" 2)
(add-edge! northern-line "balham" 2)
(add-edge! northern-line "tooting bec" 2)
(add-edge! northern-line "tooting broadway" 2)
(add-edge! northern-line "colliers wood" 2)
(add-edge! northern-line "south wimbledon"3)
(add-edge! northern-line "morden" 0)
(provide northern-line) ;provides the line to be accessed by other files

; Northern Line
(define northern-line-high-barnet-via-bank (make-mutable-graph))
(add-edge! northern-line-high-barnet-via-bank "high barnet" 4)
(add-edge! northern-line-high-barnet-via-bank "totteridge & whetstone" 2)
(add-edge! northern-line-high-barnet-via-bank "woodside park" 2)
(add-edge! northern-line-high-barnet-via-bank "west finchley" 2)
(add-edge! northern-line-high-barnet-via-bank "finchley central" 3)
(add-edge! northern-line-high-barnet-via-bank "east finchley" 2)
(add-edge! northern-line-high-barnet-via-bank "highgate" 3)
(add-edge! northern-line-high-barnet-via-bank "archway" 2)
(add-edge! northern-line-high-barnet-via-bank "tufnell park" 2)
(add-edge! northern-line-high-barnet-via-bank "kentish town" 2)
(add-edge! northern-line-high-barnet-via-bank "camden town" 2)
(add-edge! northern-line-high-barnet-via-bank "chalk farm" 2)
(add-edge! northern-line-high-barnet-via-bank "belsize park" 2)
(add-edge! northern-line-high-barnet-via-bank "hampstead" 4)
(add-edge! northern-line-high-barnet-via-bank "golders green" 3)
(add-edge! northern-line-high-barnet-via-bank "brent cross" 2)
(add-edge! northern-line-high-barnet-via-bank "hendon central" 3)
(add-edge! northern-line-high-barnet-via-bank "colindale" 2)
(add-edge! northern-line-high-barnet-via-bank "burnt oak" 3)
(add-edge! northern-line-high-barnet-via-bank "camden town" 2)
(add-edge! northern-line-high-barnet-via-bank "mornington crescent" 1)
(add-edge! northern-line-high-barnet-via-bank "euston" 2)
(add-edge! northern-line-high-barnet-via-bank "kings cross st pancras" 2)
(add-edge! northern-line-high-barnet-via-bank "angel" 3)
(add-edge! northern-line-high-barnet-via-bank "old street" 2)
(add-edge! northern-line-high-barnet-via-bank "moorgate" 2)
(add-edge! northern-line-high-barnet-via-bank "bank" 2)
(add-edge! northern-line-high-barnet-via-bank "london bridge" 1)
(add-edge! northern-line-high-barnet-via-bank "borough" 2)
(add-edge! northern-line-high-barnet-via-bank "elephant & castle" 2)
(add-edge! northern-line-high-barnet-via-bank "kennington" 2)
(add-edge! northern-line-high-barnet-via-bank "oval" 2)
(add-edge! northern-line-high-barnet-via-bank "stockwell" 2)
(add-edge! northern-line-high-barnet-via-bank "clapham north" 1)
(add-edge! northern-line-high-barnet-via-bank "clapham common" 2)
(add-edge! northern-line-high-barnet-via-bank "clapham south" 2)
(add-edge! northern-line-high-barnet-via-bank "balham" 2)
(add-edge! northern-line-high-barnet-via-bank "tooting bec" 2)
(add-edge! northern-line-high-barnet-via-bank "tooting broadway" 2)
(add-edge! northern-line-high-barnet-via-bank "colliers wood" 2)
(add-edge! northern-line-high-barnet-via-bank "south wimbledon"3)
(add-edge! northern-line-high-barnet-via-bank "morden" 0)
(provide northern-line-high-barnet-via-bank)


; Northern Line
(define northern-line-mill-hill-east-via-bank (make-mutable-graph))
(add-edge! northern-line-mill-hill-east-via-bank "mill hill east" 4)
(add-edge! northern-line-mill-hill-east-via-bank "finchley central" 3)
(add-edge! northern-line-mill-hill-east-via-bank "east finchley" 2)
(add-edge! northern-line-mill-hill-east-via-bank "highgate" 3)
(add-edge! northern-line-mill-hill-east-via-bank "archway" 2)
(add-edge! northern-line-mill-hill-east-via-bank "tufnell park" 2)
(add-edge! northern-line-mill-hill-east-via-bank "kentish town" 2)
(add-edge! northern-line-mill-hill-east-via-bank "camden town" 2)
(add-edge! northern-line-mill-hill-east-via-bank "chalk farm" 2)
(add-edge! northern-line-mill-hill-east-via-bank "belsize park" 2)
(add-edge! northern-line-mill-hill-east-via-bank "hampstead" 4)
(add-edge! northern-line-mill-hill-east-via-bank "golders green" 3)
(add-edge! northern-line-mill-hill-east-via-bank "brent cross" 2)
(add-edge! northern-line-mill-hill-east-via-bank "hendon central" 3)
(add-edge! northern-line-mill-hill-east-via-bank "colindale" 2)
(add-edge! northern-line-mill-hill-east-via-bank "burnt oak" 3)
(add-edge! northern-line-mill-hill-east-via-bank "camden town" 2)
(add-edge! northern-line-mill-hill-east-via-bank "mornington crescent" 1)
(add-edge! northern-line-mill-hill-east-via-bank "euston" 2)
(add-edge! northern-line-mill-hill-east-via-bank "kings cross st pancras" 2)
(add-edge! northern-line-mill-hill-east-via-bank "angel" 3)
(add-edge! northern-line-mill-hill-east-via-bank "old street" 2)
(add-edge! northern-line-mill-hill-east-via-bank "moorgate" 2)
(add-edge! northern-line-mill-hill-east-via-bank "bank" 2)
(add-edge! northern-line-mill-hill-east-via-bank "london bridge" 1)
(add-edge! northern-line-mill-hill-east-via-bank "borough" 2)
(add-edge! northern-line-mill-hill-east-via-bank"elephant & castle" 2)
(add-edge! northern-line-mill-hill-east-via-bank "kennington" 2)
(add-edge! northern-line-mill-hill-east-via-bank "oval" 2)
(add-edge! northern-line-mill-hill-east-via-bank "stockwell" 2)
(add-edge! northern-line-mill-hill-east-via-bank "clapham north" 1)
(add-edge! northern-line-mill-hill-east-via-bank "clapham common" 2)
(add-edge! northern-line-mill-hill-east-via-bank "clapham south" 2)
(add-edge! northern-line-mill-hill-east-via-bank "balham" 2)
(add-edge! northern-line-mill-hill-east-via-bank "tooting bec" 2)
(add-edge! northern-line-mill-hill-east-via-bank "tooting broadway" 2)
(add-edge! northern-line-mill-hill-east-via-bank "colliers wood" 2)
(add-edge! northern-line-mill-hill-east-via-bank "south wimbledon"3)
(add-edge! northern-line-mill-hill-east-via-bank "morden" 0)
(provide northern-line-mill-hill-east-via-bank)


; Northern Line
(define northern-line-edgware-via-bank (make-mutable-graph))
(add-edge! northern-line-edgware-via-bank "edgware" 4)
(add-edge! northern-line-edgware-via-bank "burnt oak" 3)
(add-edge! northern-line-edgware-via-bank "colindale" 3)
(add-edge! northern-line-edgware-via-bank "hendon central" 3)
(add-edge! northern-line-edgware-via-bank "brent cross" 3)
(add-edge! northern-line-edgware-via-bank "golders green" 3)
(add-edge! northern-line-edgware-via-bank "hampstead" 3)
(add-edge! northern-line-edgware-via-bank "belsize park" 3)
(add-edge! northern-line-edgware-via-bank "chalk farm" 3)
(add-edge! northern-line-edgware-via-bank "camden town" 2)
(add-edge! northern-line-edgware-via-bank "mornington crescent" 1)
(add-edge! northern-line-edgware-via-bank "euston" 2)
(add-edge! northern-line-edgware-via-bank "kings cross st pancras" 2)
(add-edge! northern-line-edgware-via-bank "angel" 3)
(add-edge! northern-line-edgware-via-bank "old street" 2)
(add-edge! northern-line-edgware-via-bank "moorgate" 2)
(add-edge! northern-line-edgware-via-bank "bank" 2)
(add-edge! northern-line-edgware-via-bank "london bridge" 1)
(add-edge! northern-line-edgware-via-bank "borough" 2)
(add-edge! northern-line-edgware-via-bank "elephant & castle" 2)
(add-edge! northern-line-edgware-via-bank "kennington" 2)
(add-edge! northern-line-edgware-via-bank "oval" 2)
(add-edge! northern-line-edgware-via-bank "stockwell" 2)
(add-edge! northern-line-edgware-via-bank "clapham north" 1)
(add-edge! northern-line-edgware-via-bank "clapham common" 2)
(add-edge! northern-line-edgware-via-bank "clapham south" 2)
(add-edge! northern-line-edgware-via-bank "balham" 2)
(add-edge! northern-line-edgware-via-bank "tooting bec" 2)
(add-edge! northern-line-edgware-via-bank "tooting broadway" 2)
(add-edge! northern-line-edgware-via-bank "colliers wood" 2)
(add-edge! northern-line-edgware-via-bank "south wimbledon"3)
(add-edge! northern-line-edgware-via-bank "morden" 0)
(provide northern-line-edgware-via-bank) ;provides the line to be accessed by other files


; Northern Line
(define northern-line-high-barnet-via-warren-street (make-mutable-graph))
(add-edge! northern-line-high-barnet-via-warren-street "high barnet" 4)
(add-edge! northern-line-high-barnet-via-warren-street "totteridge & whetstone" 2)
(add-edge! northern-line-high-barnet-via-warren-street "woodside park" 2)
(add-edge! northern-line-high-barnet-via-warren-street "west finchley" 2)
(add-edge! northern-line-high-barnet-via-warren-street "finchley central" 3)
(add-edge! northern-line-high-barnet-via-warren-street "east finchley" 2)
(add-edge! northern-line-high-barnet-via-warren-street "highgate" 3)
(add-edge! northern-line-high-barnet-via-warren-street "archway" 2)
(add-edge! northern-line-high-barnet-via-warren-street "tufnell park" 2)
(add-edge! northern-line-high-barnet-via-warren-street "kentish town" 2)
(add-edge! northern-line-high-barnet-via-warren-street "camden town" 2)
(add-edge! northern-line-high-barnet-via-warren-street "chalk farm" 2)
(add-edge! northern-line-high-barnet-via-warren-street "belsize park" 2)
(add-edge! northern-line-high-barnet-via-warren-street "hampstead" 4)
(add-edge! northern-line-high-barnet-via-warren-street "golders green" 3)
(add-edge! northern-line-high-barnet-via-warren-street "brent cross" 2)
(add-edge! northern-line-high-barnet-via-warren-street "hendon central" 3)
(add-edge! northern-line-high-barnet-via-warren-street "colindale" 2)
(add-edge! northern-line-high-barnet-via-warren-street "burnt oak" 3)
(add-edge! northern-line-high-barnet-via-warren-street "camden town" 2)
(add-edge! northern-line-high-barnet-via-warren-street "mornington crescent" 1)
(add-edge! northern-line-high-barnet-via-warren-street "euston" 2)
(add-edge! northern-line-high-barnet-via-warren-street "warren street" 2)
(add-edge! northern-line-high-barnet-via-warren-street "goodge street" 1)
(add-edge! northern-line-high-barnet-via-warren-street "tottenham court road" 1)
(add-edge! northern-line-high-barnet-via-warren-street "leicester square" 2)
(add-edge! northern-line-high-barnet-via-warren-street "charing cross" 1)
(add-edge! northern-line-high-barnet-via-warren-street "embankment" 2)
(add-edge! northern-line-high-barnet-via-warren-street "waterloo" 3)
(add-edge! northern-line-high-barnet-via-warren-street "kennington" 2)
(add-edge! northern-line-high-barnet-via-warren-street "oval" 2)
(add-edge! northern-line-high-barnet-via-warren-street "stockwell" 2)
(add-edge! northern-line-high-barnet-via-warren-street "clapham north" 1)
(add-edge! northern-line-high-barnet-via-warren-street "clapham common" 2)
(add-edge! northern-line-high-barnet-via-warren-street "clapham south" 2)
(add-edge! northern-line-high-barnet-via-warren-street "balham" 2)
(add-edge! northern-line-high-barnet-via-warren-street "tooting bec" 2)
(add-edge! northern-line-high-barnet-via-warren-street "tooting broadway" 2)
(add-edge! northern-line-high-barnet-via-warren-street "colliers wood" 2)
(add-edge! northern-line-high-barnet-via-warren-street "south wimbledon"3)
(add-edge! northern-line-high-barnet-via-warren-street "morden" 0)
(provide northern-line-high-barnet-via-warren-street)


; Northern Line
(define northern-line-mill-hill-east-via-warren-street (make-mutable-graph))
(add-edge! northern-line-mill-hill-east-via-warren-street "mill hill east" 4)
(add-edge! northern-line-mill-hill-east-via-warren-street "finchley central" 3)
(add-edge! northern-line-mill-hill-east-via-warren-street "east finchley" 2)
(add-edge! northern-line-mill-hill-east-via-warren-street "highgate" 3)
(add-edge! northern-line-mill-hill-east-via-warren-street "archway" 2)
(add-edge! northern-line-mill-hill-east-via-warren-street "tufnell park" 2)
(add-edge! northern-line-mill-hill-east-via-warren-street "kentish town" 2)
(add-edge! northern-line-mill-hill-east-via-warren-street "camden town" 2)
(add-edge! northern-line-mill-hill-east-via-warren-street "chalk farm" 2)
(add-edge! northern-line-mill-hill-east-via-warren-street "belsize park" 2)
(add-edge! northern-line-mill-hill-east-via-warren-street "hampstead" 4)
(add-edge! northern-line-mill-hill-east-via-warren-street "golders green" 3)
(add-edge! northern-line-mill-hill-east-via-warren-street "brent cross" 2)
(add-edge! northern-line-mill-hill-east-via-warren-street "hendon central" 3)
(add-edge! northern-line-mill-hill-east-via-warren-street "colindale" 2)
(add-edge! northern-line-mill-hill-east-via-warren-street "burnt oak" 3)
(add-edge! northern-line-mill-hill-east-via-warren-street "camden town" 2)
(add-edge! northern-line-mill-hill-east-via-warren-street "mornington crescent" 1)
(add-edge! northern-line-mill-hill-east-via-warren-street "euston" 2)
(add-edge! northern-line-mill-hill-east-via-warren-street "warren street" 2)
(add-edge! northern-line-mill-hill-east-via-warren-street "goodge street" 1)
(add-edge! northern-line-mill-hill-east-via-warren-street "tottenham court road" 1)
(add-edge! northern-line-mill-hill-east-via-warren-street "leicester square" 2)
(add-edge! northern-line-mill-hill-east-via-warren-street "charing cross" 1)
(add-edge! northern-line-mill-hill-east-via-warren-street "embankment" 2)
(add-edge! northern-line-mill-hill-east-via-warren-street "waterloo" 3)
(add-edge! northern-line-mill-hill-east-via-warren-street "kennington" 2)
(add-edge! northern-line-mill-hill-east-via-warren-street "oval" 2)
(add-edge! northern-line-mill-hill-east-via-warren-street "stockwell" 2)
(add-edge! northern-line-mill-hill-east-via-warren-street "clapham north" 1)
(add-edge! northern-line-mill-hill-east-via-warren-street "clapham common" 2)
(add-edge! northern-line-mill-hill-east-via-warren-street "clapham south" 2)
(add-edge! northern-line-mill-hill-east-via-warren-street "balham" 2)
(add-edge! northern-line-mill-hill-east-via-warren-street "tooting bec" 2)
(add-edge! northern-line-mill-hill-east-via-warren-street "tooting broadway" 2)
(add-edge! northern-line-mill-hill-east-via-warren-street "colliers wood" 2)
(add-edge! northern-line-mill-hill-east-via-warren-street "south wimbledon"3)
(add-edge! northern-line-mill-hill-east-via-warren-street "morden" 0)
(provide northern-line-mill-hill-east-via-warren-street)


; Northern Line
(define northern-line-edgware-via-warren-street (make-mutable-graph))
(add-edge! northern-line-edgware-via-warren-street "edgware" 4)
(add-edge! northern-line-edgware-via-warren-street "burnt oak" 3)
(add-edge! northern-line-edgware-via-warren-street "colindale" 3)
(add-edge! northern-line-edgware-via-warren-street "hendon central" 3)
(add-edge! northern-line-edgware-via-warren-street "brent cross" 3)
(add-edge! northern-line-edgware-via-warren-street "golders green" 3)
(add-edge! northern-line-edgware-via-warren-street "hampstead" 3)
(add-edge! northern-line-edgware-via-warren-street "belsize park" 3)
(add-edge! northern-line-edgware-via-warren-street "chalk farm" 3)
(add-edge! northern-line-edgware-via-warren-street "camden town" 2)
(add-edge! northern-line-edgware-via-warren-street "mornington crescent" 1)
(add-edge! northern-line-edgware-via-warren-street "euston" 2)
(add-edge! northern-line-edgware-via-warren-street "warren street" 2)
(add-edge! northern-line-edgware-via-warren-street "goodge street" 1)
(add-edge! northern-line-edgware-via-warren-street "tottenham court road" 1)
(add-edge! northern-line-edgware-via-warren-street "leicester square" 2)
(add-edge! northern-line-edgware-via-warren-street "charing cross" 1)
(add-edge! northern-line-edgware-via-warren-street "embankment" 2)
(add-edge! northern-line-edgware-via-warren-street "waterloo" 3)
(add-edge! northern-line-edgware-via-warren-street "kennington" 2)
(add-edge! northern-line-edgware-via-warren-street "oval" 2)
(add-edge! northern-line-edgware-via-warren-street "stockwell" 2)
(add-edge! northern-line-edgware-via-warren-street "clapham north" 1)
(add-edge! northern-line-edgware-via-warren-street "clapham common" 2)
(add-edge! northern-line-edgware-via-warren-street "clapham south" 2)
(add-edge! northern-line-edgware-via-warren-street "balham" 2)
(add-edge! northern-line-edgware-via-warren-street "tooting bec" 2)
(add-edge! northern-line-edgware-via-warren-street "tooting broadway" 2)
(add-edge! northern-line-edgware-via-warren-street "colliers wood" 2)
(add-edge! northern-line-edgware-via-warren-street "south wimbledon"3)
(add-edge! northern-line-edgware-via-warren-street "morden" 0)
(provide northern-line-edgware-via-warren-street) ;provides the line to be accessed by other files


; Bakerloo Line
(define bakerloo-line (make-mutable-graph))
(add-edge! bakerloo-line "harrow & wealdstone" 3)
(add-edge! bakerloo-line "kenton" 2)
(add-edge! bakerloo-line "south kenton" 1)
(add-edge! bakerloo-line "north wembley" 2)
(add-edge! bakerloo-line "wembley central"  3)
(add-edge! bakerloo-line "stonebridge park" 2)
(add-edge! bakerloo-line "harlesden" 2)
(add-edge! bakerloo-line "willesden junction"  3)
(add-edge! bakerloo-line "kensal green" 3)
(add-edge! bakerloo-line "queens park"  2)
(add-edge! bakerloo-line "kilburn park"  1)
(add-edge! bakerloo-line "maida vale" 2)
(add-edge! bakerloo-line "warwick avenue" 2)
(add-edge! bakerloo-line "paddington" 2)
(add-edge! bakerloo-line "edgeware road" 1)
(add-edge! bakerloo-line "marylebone" 1)
(add-edge! bakerloo-line "baker street" 2)
(add-edge! bakerloo-line "regents park" 2)
(add-edge! bakerloo-line "oxford circus" 2)
(add-edge! bakerloo-line "piccadilly circus" 2)
(add-edge! bakerloo-line "charing cross" 1)
(add-edge! bakerloo-line "embankment" 1)
(add-edge! bakerloo-line "waterloo" 2)
(add-edge! bakerloo-line "lambeth north" 2)
(add-edge! bakerloo-line "elephant & castle" 0)
(provide bakerloo-line) ;provides the line to be accessed by other files


; Central Line
(define central-line (make-mutable-graph))
(add-edge! central-line "west ruislip" 4)
(add-edge! central-line "ruislip gardens" 2)
(add-edge! central-line "south ruislip" 3)
(add-edge! central-line "northolt" 2)
(add-edge! central-line "greenford" 3)
(add-edge! central-line "perivale" 3)
(add-edge! central-line "hanger lane" 3)
(add-edge! central-line "north acton" 3)
(add-edge! central-line "east acton" 3)
(add-edge! central-line "white city" 2)
(add-edge! central-line "shepherds bush" 2)
(add-edge! central-line "holland park" 1)
(add-edge! central-line "notting hill gate" 2)
(add-edge! central-line "queensway" 2)
(add-edge! central-line "lancaster gate" 2)
(add-edge! central-line "marble arch" 1)
(add-edge! central-line "bond street" 2)
(add-edge! central-line "oxford circus" 1)
(add-edge! central-line "tottenham court road" 2)
(add-edge! central-line "holborn" 2)
(add-edge! central-line "chancery lane" 2)
(add-edge! central-line "st pauls" 2)
(add-edge! central-line "bank" 2)
(add-edge! central-line "liverpool street" 3)
(add-edge! central-line "bethnal green" 3)
(add-edge! central-line "mile end" 4)
(add-edge! central-line "stratford" 3)
(add-edge! central-line "leyton" 2)
(add-edge! central-line "leytonstone" 3)
(add-edge! central-line "snaresbrook" 2)
(add-edge! central-line "south woodford" 2)
(add-edge! central-line "woodford" 4)
(add-edge! central-line "buckhurst hill" 2)
(add-edge! central-line "loughton" 4)
(add-edge! central-line "debden" 4)
(add-edge! central-line "theydon bois" 3)
(add-edge! central-line "epping" 0)
(provide central-line) ;provides the line to be accessed by other files

; Circle Line
(define circle-line (make-mutable-graph))
(add-edge! circle-line "paddington" 2)
(add-edge! circle-line "edgware road" 2)
(add-edge! circle-line "baker street" 2)
(add-edge! circle-line "great portland street" 2)
(add-edge! circle-line "euston square" 2)
(add-edge! circle-line "kings cross st pancras" 3)
(add-edge! circle-line "farringdon" 2)
(add-edge! circle-line "barbican" 1)
(add-edge! circle-line "moorgate" 2)
(add-edge! circle-line "liverpool street"  2)
(add-edge! circle-line "aldgate" 2)
(add-edge! circle-line "tower hill" 2)
(add-edge! circle-line "monument" 1)
(add-edge! circle-line "cannon street" 1)
(add-edge! circle-line "mansion house" 1)
(add-edge! circle-line "blackfriars" 2)
(add-edge! circle-line "temple" 1)
(add-edge! circle-line "embankment" 2)
(add-edge! circle-line "westminster" 1)
(add-edge! circle-line "st jamess park" 2)
(add-edge! circle-line "victoria" 2)
(add-edge! circle-line "sloane square" 2)
(add-edge! circle-line "south kensington" 2)
(add-edge! circle-line "gloucester road" 3)
(add-edge! circle-line "high street kensington" 2)
(add-edge! circle-line "notting hill gate" 2)
(add-edge! circle-line "bayswater" 2)
(add-edge! circle-line "paddington" 0)
(provide circle-line) ;provides the line to be accessed by other files

; District Line
(define district-line (make-mutable-graph))
(add-edge! district-line "ealing broadway" 3)
(add-edge! district-line "ealing common" 2)
(add-edge! district-line "acton town" 2)
(add-edge! district-line "chiswick park" 2)
(add-edge! district-line "turnham green" 2)
(add-edge! district-line "stamford brook" 1)
(add-edge! district-line "ravenscourt park" 2)
(add-edge! district-line "hammersmith" 1)
(add-edge! district-line "barons court" 2)
(add-edge! district-line "west kensington" 2)
(add-edge! district-line "earls court" 2)
(add-edge! district-line "gloucester road" 2)
(add-edge! district-line "south kensington" 2)
(add-edge! district-line "sloane square" 2)
(add-edge! district-line "victoria" 2)
(add-edge! district-line "st jamess park" 1)
(add-edge! district-line "westminster" 2)
(add-edge! district-line "embankment" 1)
(add-edge! district-line "temple" 2)
(add-edge! district-line "blackfriars" 1)
(add-edge! district-line "mansion house" 1)
(add-edge! district-line "cannon street" 1)
(add-edge! district-line "monument" 2)
(add-edge! district-line "tower hill" 2)
(add-edge! district-line "aldgate east" 2)
(add-edge! district-line "whitechapel" 2)
(add-edge! district-line "stepney green" 2)
(add-edge! district-line "mile end" 2)
(add-edge! district-line "bow road" 2)
(add-edge! district-line "bromley-by-bow" 2)
(add-edge! district-line "west ham" 1)
(add-edge! district-line "plaistow" 2)
(add-edge! district-line "upton park" 2)
(add-edge! district-line "east ham" 3)
(add-edge! district-line "barking" 2)
(add-edge! district-line "upney" 3)
(add-edge! district-line "becontree" 2)
(add-edge! district-line "dagenham heathway" 2)
(add-edge! district-line "dagenham east" 3)
(add-edge! district-line "elm park" 2)
(add-edge! district-line "hornchurch" 2)
(add-edge! district-line "upminster bridge" 2)
(add-edge! district-line "upminster" 0)
(provide district-line) ;provides the line to be accessed by other files


; Hammersmith & City Line
(define hammersmith-city-line (make-mutable-graph))
(add-edge! hammersmith-city-line "hammersmith" 2)
(add-edge! hammersmith-city-line "goldhawk road" 1)
(add-edge! hammersmith-city-line "shepherds bush" 2)
(add-edge! hammersmith-city-line "latimer road" 1)
(add-edge! hammersmith-city-line "ladbroke grove" 2)
(add-edge! hammersmith-city-line "westbourne park" 2)
(add-edge! hammersmith-city-line "royal oak" 1)
(add-edge! hammersmith-city-line "paddington" 2)
(add-edge! hammersmith-city-line "edgware road" 2)
(add-edge! hammersmith-city-line "baker street" 2)
(add-edge! hammersmith-city-line "great portland street" 2)
(add-edge! hammersmith-city-line "euston square" 2)
(add-edge! hammersmith-city-line "kings cross st pancras" 3)
(add-edge! hammersmith-city-line "farringdon" 2)
(add-edge! hammersmith-city-line "barbican" 1)
(add-edge! hammersmith-city-line "moorgate" 2)
(add-edge! hammersmith-city-line "liverpool street" 2)
(add-edge! hammersmith-city-line "aldgate east" 2)
(add-edge! hammersmith-city-line "whitechapel" 2)
(add-edge! hammersmith-city-line "stepney green" 2)
(add-edge! hammersmith-city-line "mile end" 2)
(add-edge! hammersmith-city-line "bow road" 2)
(add-edge! hammersmith-city-line "bromley-by-bow" 2)
(add-edge! hammersmith-city-line "west ham" 1)
(add-edge! hammersmith-city-line "plaistow" 2)
(add-edge! hammersmith-city-line "upton park" 2)
(add-edge! hammersmith-city-line "east ham" 3)
(add-edge! hammersmith-city-line "barking" 0)
(provide hammersmith-city-line) ;provides the line to be accessed by other files

; Jubilee Line
(define jubilee-line (make-mutable-graph))
(add-edge! jubilee-line "stratford" 3)
(add-edge! jubilee-line "west ham" 3)
(add-edge! jubilee-line "canning town" 3)
(add-edge! jubilee-line "north greenwich" 2)
(add-edge! jubilee-line "canary wharf" 3)
(add-edge! jubilee-line "canada water" 2)
(add-edge! jubilee-line "bermondsey" 3)
(add-edge! jubilee-line "london bridge" 2)
(add-edge! jubilee-line "southwark" 1)
(add-edge! jubilee-line "waterloo" 2)
(add-edge! jubilee-line "westminster" 3)
(add-edge! jubilee-line "green park" 2)
(add-edge! jubilee-line "bond street" 3)
(add-edge! jubilee-line "baker street" 3)
(add-edge! jubilee-line "st johns wood" 2)
(add-edge! jubilee-line "swiss cottage" 2)
(add-edge! jubilee-line "finchley road" 1)
(add-edge! jubilee-line "west hampstead" 2)
(add-edge! jubilee-line "kilburn" 2)
(add-edge! jubilee-line "willesden green" 2)
(add-edge! jubilee-line "dollis hill" 2)
(add-edge! jubilee-line "neasden" 3)
(add-edge! jubilee-line "wembley park" 4)
(add-edge! jubilee-line "kingsbury" 2)
(add-edge! jubilee-line "queensbury" 3)
(add-edge! jubilee-line "canons park" 2)
(add-edge! jubilee-line "stanmore" 0)
(provide jubilee-line) ;provides the line to be accessed by other files

; Metropolitan Line
(define metropolitan-line (make-mutable-graph))
(add-edge! metropolitan-line "chesham" 8)
(add-edge! metropolitan-line "chalfont & latimer" 4)
(add-edge! metropolitan-line "chorleywood" 4)
(add-edge! metropolitan-line "rickmanworth" 4)
(add-edge! metropolitan-line "moor park" 4)
(add-edge! metropolitan-line "northwood" 2)
(add-edge! metropolitan-line "northwood hills" 3)
(add-edge! metropolitan-line "pinner" 2)
(add-edge! metropolitan-line "north harrow" 3)
(add-edge! metropolitan-line "harrow-on-the-hill" 2)
(add-edge! metropolitan-line "northwick park" 2)
(add-edge! metropolitan-line "preston road" 3)
(add-edge! metropolitan-line "wembley park" 7)
(add-edge! metropolitan-line "finchley road" 6)
(add-edge! metropolitan-line "baker street" 2)
(add-edge! metropolitan-line "great portland street" 2)
(add-edge! metropolitan-line "euston square" 2)
(add-edge! metropolitan-line "kings cross st pancras" 3)
(add-edge! metropolitan-line "farringdon" 2)
(add-edge! metropolitan-line "barbican" 1)
(add-edge! metropolitan-line "moorgate" 2)
(add-edge! metropolitan-line "liverpool street" 2)
(add-edge! metropolitan-line "aldgate" 0)
(provide metropolitan-line) ;provides the line to be accessed by other files

; Piccadilly Line
(define piccadilly-line (make-mutable-graph))
(add-edge! piccadilly-line "uxbridge" 3)
(add-edge! piccadilly-line "hillingdon" 2)
(add-edge! piccadilly-line "ickenham" 3)
(add-edge! piccadilly-line "ruislip" 2)
(add-edge! piccadilly-line "ruislip manor" 2)
(add-edge! piccadilly-line "eastcote" 2)
(add-edge! piccadilly-line "rayners lane" 3)
(add-edge! piccadilly-line "south harrow" 3)
(add-edge! piccadilly-line "sudbury hill" 2)
(add-edge! piccadilly-line "sudbury town" 2)
(add-edge! piccadilly-line "alperton" 3)
(add-edge! piccadilly-line "park royal" 2)
(add-edge! piccadilly-line "north ealing" 2)
(add-edge! piccadilly-line "ealing common" 2)
(add-edge! piccadilly-line "acton town" 3)
(add-edge! piccadilly-line "turnham green" 4)
(add-edge! piccadilly-line "hammersmith" 2)
(add-edge! piccadilly-line "barons court" 3)
(add-edge! piccadilly-line "earls court" 2)
(add-edge! piccadilly-line "gloucester road" 1)
(add-edge! piccadilly-line "south kensington" 3)
(add-edge! piccadilly-line "knightsbridge" 1)
(add-edge! piccadilly-line "hyde park corner" 2)
(add-edge! piccadilly-line "green park" 1)
(add-edge! piccadilly-line "piccadilly circus" 2)
(add-edge! piccadilly-line "leicester square" 1)
(add-edge! piccadilly-line "covent garden" 2)
(add-edge! piccadilly-line "holborn" 1)
(add-edge! piccadilly-line "russel square" 2)
(add-edge! piccadilly-line "kings cross st pancras" 3)
(add-edge! piccadilly-line "caledonian road" 1)
(add-edge! piccadilly-line "holloway road" 2)
(add-edge! piccadilly-line "arsenal" 1)
(add-edge! piccadilly-line "finsbury park" 2)
(add-edge! piccadilly-line "manor house" 3)
(add-edge! piccadilly-line "turnpike lane" 2)
(add-edge! piccadilly-line "wood green" 2)
(add-edge! piccadilly-line "bounds green" 3)
(add-edge! piccadilly-line "arnos grove" 3)
(add-edge! piccadilly-line "southgate" 3)
(add-edge! piccadilly-line "oakwood" 2)
(add-edge! piccadilly-line "cockfosters" 0)
(provide piccadilly-line) ;provides the line to be accessed by other files

; Victoria Line
(define victoria-line (make-mutable-graph))
(add-edge! victoria-line "walthamstow central" 2)
(add-edge! victoria-line "blackhorse road" 2)
(add-edge! victoria-line "tottenham hale" 2)
(add-edge! victoria-line "seven sisters" 4)
(add-edge! victoria-line "finsbury park" 3)
(add-edge! victoria-line "highbury & islington" 3)
(add-edge! victoria-line "kings cross st pancras" 2)
(add-edge! victoria-line "euston" 1)
(add-edge! victoria-line "warren street" 2)
(add-edge! victoria-line "oxford circus" 2)
(add-edge! victoria-line "green park" 2)
(add-edge! victoria-line "victoria" 2)
(add-edge! victoria-line "pimlico" 1)
(add-edge! victoria-line "vauxhall" 3)
(add-edge! victoria-line "stockwell" 2)
(add-edge! victoria-line "brixton" 0)
(provide victoria-line) ;provides the line to be accessed by other files

; Waterloo & City Line
(define waterloo-city-line (make-mutable-graph))
(add-edge! waterloo-city-line "waterloo" 4)
(add-edge! waterloo-city-line "bank" 0)
(provide waterloo-city-line) ;provides the line to be accessed by other files
