#lang racket/gui

(require "DijkstrasAlgorithm.rkt")
(require "Database.rkt")

(define stations
  '("High Barnet"
    "Totteridge & Whetstone"
    "Woodside Park"
    "West Finchley"
    "Finchley Central"
    "Mill Hill East"
    "East Finchley"
    "Highgate"
    "Archway"
    "Tufnell Park"
    "Kentish Town"
    "Camden Town"
    "Euston (Northern)"
    "King's Cross St. Pancras (Northern)"
    "Angel"
    "Old Street"
    "Moorgate (Northern)"
    "Bank (Northern)"
    "London Bridge (Northern)"
    "Borough"
    "Elephant & Castle (Northern)"
    "Mornington Crescent"
    "Warren Street (Northern)"
    "Goodge Street"
    "Tottenham Court Road (Northern)"
    "Leicester Square (Northern)"
    "Charing Cross"
    "Embankment (Northern)"
    "Waterloo (Northern)"
    "Kennington"
    "Chalk Farm"
    "Belsize Park"
    "Hampstead"
    "Golders Green"
    "Brent Cross"
    "Hendon Central"
    "Colindale"
    "Burnt Oak"
    "Edgware"
    "Oval"
    "Stockwell (Northern)"
    "Clapham North"
    "Clapham Common"
    "Clapham South"
    "Balham"
    "Tooting Bec"
    "Tooting Broadway"
    "Colliers Wood"
    "South Wimbledon"
    "Morden"
    "Nine Elms"
    "Battersea Power Station"
    "Harrow & Wealdstone"
    "Kenton"
    "South Kenton"
    "North Wembley"
    "Wembley Central"
    "Stonebridge Park"
    "Harlesden"
    "Willesden Junction"
    "Kensal Green"
    "Queens Park"
    "Kilburn Park"
    "Maida Vale"
    "Warwick Avenue"
    "Paddington (Bakerloo)"
    "Edgware Road"
    "Marylebone"
    "Baker Street (Bakerloo)"
    "Regents Park"
    "Oxford Circus (Bakerloo)"
    "Piccadilly Circus (Bakerloo)"
    "Charing Cross"
    "Embankment (Bakerloo)"
    "Waterloo (Bakerloo)"
    "Lambeth North"
    "Elephant & Castle (Bakerloo)"
    "West Ruislip"
    "Ruislip Gardens"
    "South Ruislip"
    "Northolt"
    "Greenford"
    "Perivale"
    "Hanger Lane"
    "North Acton"
    "West Acton"
    "Ealing Broadway (Central)"
    "East Acton"
    "White City"
    "Shepherd's Bush"
    "Holland Park"
    "Notting Hill Gate (Central)"
    "Queensway"
    "Lancaster Gate"
    "Marble Arch"
    "Bond Street (Central)"
    "Oxford Circus (Central)"
    "Tottenham Court Road (Central)"
    "Holborn (Central)"
    "Chancery Lane"
    "St. Pauls"
    "Bank (Central)"
    "Liverpool Street (Central)"
    "Bethnal Green"
    "Mile End (Central)"
    "Stratford (Central)"
    "Leyton"
    "Leytonstone"
    "Wanstead"
    "Redbridge"
    "Gants Hill"
    "Newbury Park"
    "Barkingside"
    "Fairlop"
    "Hainault"
    "Grange Hill"
    "Chigwell"
    "Roding Valley"
    "Woodford"
    "Snaresbrook"
    "South Woodford"
    "Woodford"
    "Buckhurst Hill"
    "Loughton"
    "Debden"
    "Theydon Bois"
    "Epping"
    "Paddington (Circle)"
    "Edgware Road (Circle)"
    "Baker Street (Circle)"
    "Great Portland Street (Circle)"
    "Euston Square (Circle)"
    "King's Cross St. Pancras (Circle)"
    "Farringdon (Circle)"
    "Barbican (Circle)"
    "Moorgate (Circle)"
    "Liverpool Street (Circle)"
    "Aldgate"
    "Tower Hill (Circle)"
    "Monument (Circle)"
    "Cannon Street"
    "Mansion House"
    "Blackfriars"
    "Temple"
    "Embankment (Circle)"
    "Westminster (Circle)"
    "St. James's Park"
    "Victoria (Circle)"
    "Sloane Square"
    "South Kensington (Circle)"
    "Gloucester Road (Circle)"
    "High Street Kensington (Circle)"
    "Notting Hill Gate (Circle)"
    "Bayswater"
    "Ealing Broadway (District)"
    "Ealing Common (District)"
    "Acton Town (District)"
    "Chiswick Park"
    "Turnham Green"
    "Gunnersbury"
    "Kew Gardens"
    "Richmond"
    "Stamford Brook"
    "Ravenscourt Park"
    "Hammersmith (District)"
    "Barons Court (District)"
    "West Kensington"
    "Earl's Court (District)"
    "West Brompton"
    "Fulham Broadway"
    "Parsons Green"
    "Putney Bridge"
    "East Putney"
    "Southfields"
    "Wimbledon Park"
    "Wimbledon"
    "Kensington (Olympia)"
    "High Street Kensington (District)"
    "Notting Hill Gate (District)"
    "Bayswater"
    "Paddington (District)"
    "Edgware Road (District)"
    "Gloucester Road (District)"
    "South Kensington (District)"
    "Sloane Square"
    "Victoria (District)"
    "St. James's Park"
    "Westminster (District)"
    "Embankment (District)"
    "Temple"
    "Blackfriars"
    "Mansion House"
    "Cannon Street"
    "Monument (District)"
    "Tower Hill (District)"
    "Aldgate East (District)"
    "Whitechapel"
    "Stepney Green"
    "Mile End (District)"
    "Bow Road"
    "Bromley-by-Bow"
    "West Ham (District)"
    "Plaistow"
    "Upton Park"
    "East Ham"
    "Barking (District)"
    "Upney"
    "Becontree"
    "Dagenham Heathway"
    "Dagenham East"
    "Elm Park"
    "Hornchurch"
    "Upminster Bridge"
    "Upminster"
    "Hammersmith (Hammersmith & City)"
    "Goldhawk Road"
    "Shepherd's Bush"
    "Latimer Road"
    "Ladbroke Grove"
    "Westbourne Park"
    "Royal Oak"
    "Paddington (Hammersmith & City)"
    "Edgware Road (Hammersmith & City)"
    "Baker Street (Hammersmith & City)"
    "Great Portland Street (Hammersmith & City)"
    "Euston Square (Hammersmith & City)"
    "King's Cross St. Pancras (Hammersmith & City)"
    "Farringdon (Hammersmith & City)"
    "Barbican (Hammersmith & City)"
    "Moorgate (Hammersmith & City)"
    "Liverpool Street (Hammersmith & City)"
    "Aldgate East (Hammersmith & City)"
    "Whitechapel"
    "Stepney Green"
    "Mile End (Hammersmith & City)"
    "Bow Road"
    "Bromley-by-Bow"
    "West Ham (Hammersmith & City)"
    "Plaistow"
    "Upton Park"
    "East Ham"
    "Barking (Hammersmith & City)"
    "Stratford (Jubilee)"
    "West Ham (Jubilee)"
    "Canning Town"
    "North Greenwich"
    "Canary Wharf"
    "Canada Water"
    "Bermondsey"
    "London Bridge (Jubilee)"
    "Southwark"
    "Waterloo (Jubilee)"
    "Westminster (Jubilee)"
    "Green Park (Jubilee)"
    "Bond Street (Jubilee)"
    "Baker Street (Jubilee)"
    "St. Johns Wood"
    "Swiss Cottage"
    "Finchley Road (Jubilee)"
    "West Hampstead"
    "Kilburn"
    "Willesden Green"
    "Dollis Hill"
    "Neasden"
    "Wembley Park (Jubilee)"
    "Kingsbury"
    "Queensbury"
    "Canons Park"
    "Stanmore"
    "Chesham"
    "Chalfont & Latimer"
    "Amersham"
    "Chorleywood"
    "Rickmansworth"
    "Moor Park"
    "Croxley"
    "Watford"
    "Northwood"
    "Northwood Hills"
    "Pinner"
    "North Harrow"
    "Harrow-on-the-Hill"
    "West Harrow"
    "Rayners Lane (Metropolitan)"
    "Eastcote"
    "Ruislip Manor"
    "Ruislip"
    "Ickenham"
    "Hillingdon"
    "Harrow-on-the-Hill"
    "Northwick Park"
    "Preston Road"
    "Wembley Park (Metropolitan)"
    "Finchley Road (Metropolitan)"
    "Baker Street (Metropolitan)"
    "Great Portland Street"
    "Euston Square"
    "King's Cross St. Pancras (Metropolitan)"
    "Farringdon"
    "Barbican"
    "Moorgate (Metropolitan)"
    "Liverpool Street (Metropolitan)"
    "Aldgate"
    "Uxbridge"
    "Hillingdon"
    "Ickenham"
    "Ruislip"
    "Ruislip Manor"
    "Eastcote"
    "Rayners Lane (Piccadilly)"
    "South Harrow"
    "Sudbury Hill"
    "Sudbury Town"
    "Alperton"
    "Park Royal"
    "North Ealing"
    "Ealing Common (Piccadilly)"
    "Acton Town (Piccadilly)"
    "South Ealing"
    "Northfields"
    "Boston Manor"
    "Osterley"
    "Hounslow East"
    "Hounslow Central"
    "Hounslow West"
    "Hatton Cross"
    "Heathrow Terminal 4"
    "Heathrow Terminals 1, 2, 3"
    "Turnham Green"
    "Hammersmith (Piccadilly)"
    "Barons Court (Piccadilly)"
    "Earl's Court (Piccadilly)"
    "Gloucester Road (Piccadilly)"
    "South Kensington (Piccadilly)"
    "Knightsbridge"
    "Hyde Park Corner"
    "Green Park (Piccadilly)"
    "Piccadilly Circus (Piccadilly)"
    "Leicester Square (Piccadilly)"
    "Covent Garden"
    "Holborn (Piccadilly)"
    "Russell Square"
    "King's Cross St. Pancras (Piccadilly)"
    "Caledonian Road"
    "Holloway Road"
    "Arsenal"
    "Finsbury Park (Piccadilly)"
    "Manor House"
    "Turnpike Lane"
    "Wood Green"
    "Bounds Green"
    "Arnos Grove"
    "Southgate"
    "Oakwood"
    "Cockfosters"
    "Walthamstow Central"
    "Blackhorse Road"
    "Tottenham Hale"
    "Seven Sisters"
    "Finsbury Park (Victoria)"
    "Highbury & Islington"
    "King's Cross St. Pancras (Victoria)"
    "Euston (Victoria)"
    "Warren Street (Victoria)"
    "Oxford Circus (Victoria)"
    "Green Park (Victoria)"
    "Victoria (Victoria)"
    "Pimlico"
    "Vauxhall"
    "Stockwell (Victoria)"
    "Brixton"
    "Waterloo (Waterloo & City)"
    "Bank (Waterloo & City)"))


(define frame (new frame%
                   [label "Station Selector"]
                   [width 400]
                   [height 600]))

(define start-station-dropdown (new choice% [parent frame]
                                    [label "Start Station"]
                                    [choices stations]))

(define final-station-dropdown (new choice% [parent frame]
                                    [label "Final Station"]
                                    [choices stations]))

(define button (new button% [parent frame]
                    [label "Submit"]
                    [callback (lambda (button event)
                                (on-button-click))]))

(define text-output (new text-field% [parent frame]
                         [label "Output will be displayed here"]
                         [style '(multiple)]
                         [min-height 200]
                         [stretchable-height #t]))

(define (on-button-click)
  (let ((start-station (send start-station-dropdown get-string-selection))
        (final-station (send final-station-dropdown get-string-selection)))
    
    (define-values (result final-distance) (dijkstra tfl-line start-station final-station))

    ; Build a string with all stations in order (Start to Finish)
    (define stations-string (string-join (map (lambda (item) (format "~a" item)) result) "\n"))

    ; Build the final distance string
    (define final-distance-string (format "\n\nFinal Time: ~a" final-distance))

    ; Update the text-output with the output
    (send text-output set-value (string-append stations-string final-distance-string))))

(send frame show #t)