#lang racket


; Allows for the creation of a hash table to store the stations, their neighbors 
; and the time to travel to the next station
(define (make-mutable-graph)
  (make-hash '()))

; Adds the edge (connection between stations) to the vertexes (stations)
(define (add-edge! graph vertex1 vertex2 weight)
  (define new-edges (cons (list vertex1 vertex2 weight) (hash-ref graph 'edges '())))
  (hash-set! graph 'edges new-edges))

; Returns the neighbors of a given station, could be used to get a route if done right
; This also returns all neighbors, even the ones going backwards or forwards
(define (get-neighbors graph vertex)
  (define edges (hash-ref graph 'edges '()))
  (define neighbors (filter (lambda (edge) (or (equal? vertex (car edge)) (equal? vertex (cadr edge)))) edges))
  (map (lambda (neighbor) 
         (if (equal? vertex (car neighbor))
             (list (cadr neighbor) (caddr neighbor))
             (list (car neighbor) (caddr neighbor))))
       neighbors))

; Gets the weight (time) between the vertexes (stations), could be used to get the approximate time 
; to get from station a to station b
(define (get-weight graph vertex1 vertex2)
  (define edges (hash-ref graph 'edges '()))
  (define weight (ormap
                  (lambda (edge)
                    (if (equal? vertex1 (car edge)) 
                        (if (equal? vertex2 (cadr edge)) (caddr edge) #f)
                        (if (equal? vertex1 (cadr edge)) (caddr edge) #f)))
                  edges))
  weight)


; If the program is to find connections between the lines, then the defines would have to change into 
; one unison name like "london-tube-network" or something like that, atm to make things clearer they 
; are separate to know which lines are done

; Northern Line
(define northern-line (make-mutable-graph))
(add-edge! northern-line "high barnet" "totteridge & whetstone" 4)
(add-edge! northern-line "totteridge & whetstone" "woodside park" 2)
(add-edge! northern-line "woodside park" "west finchley" 2)
(add-edge! northern-line "west finchley" "finchley central" 2)
(add-edge! northern-line "finchley central" "mill hill east" 3)
(add-edge! northern-line "finchley central" "east finchley" 4)
(add-edge! northern-line "east finchley" "highgate" 2)
(add-edge! northern-line "highgate" "archway" 3)
(add-edge! northern-line "archway" "tufnell park" 2)
(add-edge! northern-line "tufnell park" "kentish town" 2)
(add-edge! northern-line "kentish town" "camden town" 2)
(add-edge! northern-line "camden town" "chalk farm" 2)
(add-edge! northern-line "chalk farm" "belsize park" 2)
(add-edge! northern-line "belsize park" "hampstead" 2)
(add-edge! northern-line "hampstead" "golders green" 4)
(add-edge! northern-line "golders green" "brent cross" 3)
(add-edge! northern-line "brent cross" "hendon central" 2)
(add-edge! northern-line "hendon central" "colindale" 3)
(add-edge! northern-line "colindale" "burnt oak" 2)
(add-edge! northern-line "burnt oak" "edgeware" 3)
(add-edge! northern-line "camden town" "euston" 3)
(add-edge! northern-line "camden town" "mornington crescent" 2)
(add-edge! northern-line "mornington crescent" "euston" 1)
(add-edge! northern-line "euston" "kings cross st pancras" 2)
(add-edge! northern-line "kings cross st pancras" "angel" 2)
(add-edge! northern-line "angel" "old street" 3)
(add-edge! northern-line "old street" "moorgate" 2)
(add-edge! northern-line "moorgate" "bank" 2)
(add-edge! northern-line "bank" "london bridge" 2)
(add-edge! northern-line "london bridge" "borough" 1)
(add-edge! northern-line "borough" "elephant & castle" 2)
(add-edge! northern-line "elephant & castle" "kennington" 2)
(add-edge! northern-line "euston" "warren street" 1)
(add-edge! northern-line "warren street" "goodge street" 2)
(add-edge! northern-line "goodge street" "tottenham court road" 1)
(add-edge! northern-line "tottenham court road" "leicester square" 1)
(add-edge! northern-line "leicester square" "charing cross" 2)
(add-edge! northern-line "charing cross" "embankment" 1)
(add-edge! northern-line "embankment" "waterloo" 2)
(add-edge! northern-line "waterloo" "kennington" 3)
(add-edge! northern-line "kennington" "nine elms" 2)                ; No given off-peak times
(add-edge! northern-line "nine elms" "battersea power station" 2)   ; No given off-peak times
(add-edge! northern-line "kennington" "oval" 2)
(add-edge! northern-line "oval" "stockwell" 2)
(add-edge! northern-line "stockwell" "clapham north" 2)
(add-edge! northern-line "clapham north" "clapham common" 1)
(add-edge! northern-line "clapham common" "clapham south" 2)
(add-edge! northern-line "clapham south" "balham" 2)
(add-edge! northern-line "balham" "tooting bec" 2)
(add-edge! northern-line "tooting bec" "tooting broadway" 2)
(add-edge! northern-line "tooting broadway" "colliers wood" 2)
(add-edge! northern-line "colliers wood" "south wimbledon" 2)
(add-edge! northern-line "south wimbledon" "morden" 3)

; Bakerloo Line
(define bakerloo-line (make-mutable-graph))
(add-edge! bakerloo-line "harrow & wealdstone" "kenton" 3)
(add-edge! bakerloo-line "kenton" "south kenton" 2)
(add-edge! bakerloo-line "south kenton" "north wembley" 1)
(add-edge! bakerloo-line "north wembley" "wembley central" 2)
(add-edge! bakerloo-line "wembley central" "stonebridge park" 3)
(add-edge! bakerloo-line "stonebridge park" "harlesden" 2)
(add-edge! bakerloo-line "harlesden" "willesden junction" 2)
(add-edge! bakerloo-line "willesden junction" "kensal green" 3)
(add-edge! bakerloo-line "kensal green" "queens park" 3)
(add-edge! bakerloo-line "queens park" "kilburn park" 2)
(add-edge! bakerloo-line "kilburn park" "maida vale" 1)
(add-edge! bakerloo-line "maida vale" "warwick avenue" 2)
(add-edge! bakerloo-line "warwick avenue" "paddington" 2)
(add-edge! bakerloo-line "paddington" "edgeware road" 2)
(add-edge! bakerloo-line "edgeware road" "marylebone" 1)
(add-edge! bakerloo-line "marylebone" "baker street" 1)
(add-edge! bakerloo-line "baker street" "regents park" 2)
(add-edge! bakerloo-line "regents park" "oxford circus" 2)
(add-edge! bakerloo-line "oxford circus" "piccadilly circus" 2)
(add-edge! bakerloo-line "piccadilly circus" "charing cross" 2)
(add-edge! bakerloo-line "charing cross" "embankment" 1)
(add-edge! bakerloo-line "embankment" "waterloo" 1)
(add-edge! bakerloo-line "waterloo" "lambeth north" 2)
(add-edge! bakerloo-line "lambeth north" "elephant & castle" 2)

; Central Line
(define central-line (make-mutable-graph))
(add-edge! central-line "west ruislip" "ruislip gardens" 4)
(add-edge! central-line "ruislip gardens" "south ruislip" 2)
(add-edge! central-line "south ruislip" "northolt" 3)
(add-edge! central-line "northolt" "greenford" 2)
(add-edge! central-line "greenford" "perivale" 3)
(add-edge! central-line "perivale" "hanger lane" 3)
(add-edge! central-line "hanger lane" "north acton" 3)
(add-edge! central-line "north acton" "west acton" 3)
(add-edge! central-line "west acton" "ealing broadway" 3)
(add-edge! central-line "north acton" "east acton" 2)
(add-edge! central-line "east acton" "white city" 3)
(add-edge! central-line "white city" "shepherds bush" 2)
(add-edge! central-line "shepherds bush" "holland park" 2)
(add-edge! central-line "holland park" "notting hill gate" 1)
(add-edge! central-line "notting hill gate" "queensway" 2)
(add-edge! central-line "queensway" "lancaster gate" 2)
(add-edge! central-line "lancaster gate" "marble arch" 2)
(add-edge! central-line "marble arch" "bond street" 1)
(add-edge! central-line "bond street" "oxford circus" 2)
(add-edge! central-line "oxford circus" "tottenham court road" 1)
(add-edge! central-line "tottenham court road" "holborn" 2)
(add-edge! central-line "holborn" "chancery lane" 2)
(add-edge! central-line "chancery lane" "st pauls" 2)
(add-edge! central-line "st pauls" "bank" 2)
(add-edge! central-line "bank" "liverpool street" 2)
(add-edge! central-line "liverpool street" "bethnal green" 3)
(add-edge! central-line "bethnal green" "mile end" 3)
(add-edge! central-line "mile end" "stratford" 4)
(add-edge! central-line "stratford" "leyton" 3)
(add-edge! central-line "leyton" "leytonstone" 2)
(add-edge! central-line "leytonstone" "wanstead" 3)
(add-edge! central-line "wanstead" "redbridge" 2)
(add-edge! central-line "redbridge" "gants hill" 3)
(add-edge! central-line "gants hill" "newbury park" 4)
(add-edge! central-line "newbury park" "barkingside" 2)
(add-edge! central-line "barkingside" "fairlop" 2)
(add-edge! central-line "fairlop" "hainault" 2)
(add-edge! central-line "hainault" "grange hill" 2)
(add-edge! central-line "grange hill" "chigwell" 2)
(add-edge! central-line "chigwell" "roding valley" 4)
(add-edge! central-line "roding valley" "woodford" 3)
(add-edge! central-line "leytonstone" "snaresbrook" 3)
(add-edge! central-line "snaresbrook" "south woodford" 2)
(add-edge! central-line "south woodford" "woodford" 2)
(add-edge! central-line "woodford" "buckhurst hill" 4)
(add-edge! central-line "buckhurst hill" "loughton" 2)
(add-edge! central-line "loughton" "debden" 4)
(add-edge! central-line "debden" "theydon bois" 4)
(add-edge! central-line "theydon bois" "epping" 3)

; Circle Line
(define circle-line (make-mutable-graph))
(add-edge! circle-line "paddington" "edgware road" 2)
(add-edge! circle-line "edgware road" "baker street" 2)
(add-edge! circle-line "baker street" "great portland street" 2)
(add-edge! circle-line "great portland street" "euston square" 2)
(add-edge! circle-line "euston square" "kings cross st pancras" 2)
(add-edge! circle-line "kings cross st pancras" "farringdon" 3)
(add-edge! circle-line "farringdon" "barbican" 2)
(add-edge! circle-line "barbican" "moorgate" 1)
(add-edge! circle-line "moorgate" "liverpool street" 2)
(add-edge! circle-line "liverpool street" "aldgate" 2)
(add-edge! circle-line "aldgate" "tower hill" 2)
(add-edge! circle-line "tower hill" "monument" 2)
(add-edge! circle-line "monument" "cannon street" 1)
(add-edge! circle-line "cannon street" "mansion house" 1)
(add-edge! circle-line "mansion house" "blackfriars" 1)
(add-edge! circle-line "blackfriars" "temple" 2)
(add-edge! circle-line "temple" "embankment" 1)
(add-edge! circle-line "embankment" "westminster" 2)
(add-edge! circle-line "westminster" "st jamess park" 1)
(add-edge! circle-line "st jamess park" "victoria" 2)
(add-edge! circle-line "victoria" "sloane square" 2)
(add-edge! circle-line "sloane square" "south kensington" 2)
(add-edge! circle-line "south kensington" "gloucester road" 2)
(add-edge! circle-line "gloucester road" "high street kensington" 3)
(add-edge! circle-line "high street kensington" "notting hill gate" 2)
(add-edge! circle-line "notting hill gate" "bayswater" 2)
(add-edge! circle-line "bayswater" "paddington" 2)

; District Line
(define district-line (make-mutable-graph))
(add-edge! district-line "ealing broadway" "ealing common" 3)
(add-edge! district-line "ealing common" "acton town" 2)
(add-edge! district-line "acton town" "chiswick park" 2)
(add-edge! district-line "chiswick park" "turnham green" 2)
(add-edge! district-line "turnham green" "gunnersbury" 2)
(add-edge! district-line "gunnersbury" "kew gardens" 3)
(add-edge! district-line "kew gardens" "richmond" 3)
(add-edge! district-line "turnham green" "stamford brook" 2)
(add-edge! district-line "stamford brook" "ravenscourt park" 1)
(add-edge! district-line "ravenscourt park" "hammersmith" 2)
(add-edge! district-line "hammersmith" "barons court" 1)
(add-edge! district-line "barons court" "west kensington" 2)
(add-edge! district-line "west kensington" "earls court" 2)
(add-edge! district-line "earls court" "west brompton" 2)
(add-edge! district-line "west brompton" "fulham broadway" 1)
(add-edge! district-line "fulham broadway" "parsons green" 2)
(add-edge! district-line "parsons green" "putney bridge" 3)
(add-edge! district-line "putney bridge" "east putney" 2)
(add-edge! district-line "east putney" "southfields" 2)
(add-edge! district-line "southfields" "wimbledon park" 2)
(add-edge! district-line "wimbledon park" "wimbledon" 3)
(add-edge! district-line "earls court" "kensington (olympia)" 3)
(add-edge! district-line "earls court" "high street kensington" 3)
(add-edge! district-line "high street kensington" "notting hill gate" 2)
(add-edge! district-line "notting hill gate" "bayswater" 2)
(add-edge! district-line "bayswater" "paddington" 2)
(add-edge! district-line "paddington" "edgware road" 2)
(add-edge! district-line "earls court" "gloucester road" 2)
(add-edge! district-line "gloucester road" "south kensington" 2)
(add-edge! district-line "south kensington" "sloane square" 2)
(add-edge! district-line "sloane square" "victoria" 2)
(add-edge! district-line "victoria" "st jamess park" 2)
(add-edge! district-line "st jamess park" "westminster" 1)
(add-edge! district-line "westminster" "embankment" 2)
(add-edge! district-line "embankment" "temple" 1)
(add-edge! district-line "temple" "blackfriars" 2)
(add-edge! district-line "blackfriars" "mansion house" 1)
(add-edge! district-line "mansion house" "cannon street" 1)
(add-edge! district-line "cannon street" "monument" 1)
(add-edge! district-line "monument" "tower hill" 2)
(add-edge! district-line "tower hill" "aldgate east" 2)
(add-edge! district-line "aldgate east" "whitechapel" 2)
(add-edge! district-line "whitechapel" "stepney green" 2)
(add-edge! district-line "stepney green" "mile end" 2)
(add-edge! district-line "mile end" "bow road" 2)
(add-edge! district-line "bow road" "bromley-by-bow" 2)
(add-edge! district-line "bromley-by-bow" "west ham" 2)
(add-edge! district-line "west ham" "plaistow" 1)
(add-edge! district-line "plaistow" "upton park" 2)
(add-edge! district-line "upton park" "east ham" 2)
(add-edge! district-line "east ham" "barking" 3)
(add-edge! district-line "barking" "upney" 2)
(add-edge! district-line "upney" "becontree" 3)
(add-edge! district-line "becontree" "dagenham heathway" 2)
(add-edge! district-line "dagenham heathway" "dagenham east" 2)
(add-edge! district-line "dagenham east" "elm park" 3)
(add-edge! district-line "elm park" "hornchurch" 2)
(add-edge! district-line "hornchurch" "upminster bridge" 2)
(add-edge! district-line "upminster bridge" "upminster" 2)

; Elizabeth Line
; No given off-peak times
(define elizabeth-line (make-mutable-graph))
(add-edge! elizabeth-line "reading" "twyford" 0)
(add-edge! elizabeth-line "twyford" "maidenhead" 0)
(add-edge! elizabeth-line "maidenhead" "taplow" 0)
(add-edge! elizabeth-line "taplow" "burnham" 0)
(add-edge! elizabeth-line "burnham" "slough" 0)
(add-edge! elizabeth-line "slough" "langley" 0)
(add-edge! elizabeth-line "langley" "iver" 0)
(add-edge! elizabeth-line "iver" "west drayton" 0)
(add-edge! elizabeth-line "west drayton" "hayes & harlington" 0)
(add-edge! elizabeth-line "hayes & harlington" "terminals 2 & 3" 0)
(add-edge! elizabeth-line "terminals 2 & 3" "terminal 5" 0)
(add-edge! elizabeth-line "terminals 2 & 3" "terminal 4" 0)
(add-edge! elizabeth-line "hayes & harlington" "southall" 0)
(add-edge! elizabeth-line "southall" "hanwell" 0)
(add-edge! elizabeth-line "hanwell" "west ealing" 0)
(add-edge! elizabeth-line "west ealing" "ealing broadway" 0)
(add-edge! elizabeth-line "ealing broadway" "acton main line" 0)
(add-edge! elizabeth-line "acton main line" "paddington" 0)
(add-edge! elizabeth-line "paddington" "bond street" 0)
(add-edge! elizabeth-line "bond street" "tottenham court road" 0)
(add-edge! elizabeth-line "tottenham court road" "farringdon" 0)
(add-edge! elizabeth-line "farringdon" "liverpool street" 0)
(add-edge! elizabeth-line "liverpool street" "stratford" 0)
(add-edge! elizabeth-line "stratford" "maryland" 0)
(add-edge! elizabeth-line "maryland" "forest gate" 0)
(add-edge! elizabeth-line "forest gate" "manor park" 0)
(add-edge! elizabeth-line "manor park" "ilford" 0)
(add-edge! elizabeth-line "ilford" "seven kings" 0)
(add-edge! elizabeth-line "seven kings" "goodmayes" 0)
(add-edge! elizabeth-line "goodmayes" "chadwell heath" 0)
(add-edge! elizabeth-line "chadwell heath" "romford" 0)
(add-edge! elizabeth-line "romford" "gidea park" 0)
(add-edge! elizabeth-line "gidea park" "harold wood" 0)
(add-edge! elizabeth-line "harold wood" "brentwood" 0)
(add-edge! elizabeth-line "brentwood" "shenfield" 0)
(add-edge! elizabeth-line "liverpool street" "whitechapel" 0)
(add-edge! elizabeth-line "whitechapel" "canary wharf" 0)
(add-edge! elizabeth-line "canary wharf" "custom house" 0)
(add-edge! elizabeth-line "custom house" "woolwich" 0)
(add-edge! elizabeth-line "woolwich" "abbey wood" 0)

; Hammersmith & City Line
(define hammersmith-city-line (make-mutable-graph))
(add-edge! hammersmith-city-line "hammersmith" "goldhawk road" 2)
(add-edge! hammersmith-city-line "goldhawk road" "shepherds bush" 1)
(add-edge! hammersmith-city-line "shepherds bush" "latimer road" 2)
(add-edge! hammersmith-city-line "latimer road" "ladbroke grove" 1)
(add-edge! hammersmith-city-line "ladbroke grove" "westbourne park" 2)
(add-edge! hammersmith-city-line "westbourne park" "royal oak" 2)
(add-edge! hammersmith-city-line "royal oak" "paddington" 1)
(add-edge! hammersmith-city-line "paddington" "edgware road" 2)
(add-edge! hammersmith-city-line "edgware road" "baker street" 2)
(add-edge! hammersmith-city-line "baker street" "great portland street" 2)
(add-edge! hammersmith-city-line "great portland street" "euston square" 2)
(add-edge! hammersmith-city-line "euston square" "kings cross st pancras" 2)
(add-edge! hammersmith-city-line "kings cross st pancras" "farringdon" 3)
(add-edge! hammersmith-city-line "farringdon" "barbican" 2)
(add-edge! hammersmith-city-line "barbican" "moorgate" 1)
(add-edge! hammersmith-city-line "moorgate" "liverpool street" 2)
(add-edge! hammersmith-city-line "liverpool street" "aldgate east" 2)
(add-edge! hammersmith-city-line "aldgate east" "whitechapel" 2)
(add-edge! hammersmith-city-line "whitechapel" "stepney green" 2)
(add-edge! hammersmith-city-line "stepney green" "mile end" 2)
(add-edge! hammersmith-city-line "mile end" "bow road" 2)
(add-edge! hammersmith-city-line "bow road" "bromley-by-bow" 2)
(add-edge! hammersmith-city-line "bromley-by-bow" "west ham" 2)
(add-edge! hammersmith-city-line "west ham" "plaistow" 1)
(add-edge! hammersmith-city-line "plaistow" "upton park" 2)
(add-edge! hammersmith-city-line "upton park" "east ham" 2)
(add-edge! hammersmith-city-line "east ham" "barking" 3)

; Jubilee Line
(define jubilee-line (make-mutable-graph))
(add-edge! jubilee-line "stratford" "west ham" 3)
(add-edge! jubilee-line "west ham" "canning town" 3)
(add-edge! jubilee-line "canning town" "north greenwich" 3)
(add-edge! jubilee-line "north greenwich" "canary wharf" 2)
(add-edge! jubilee-line "canary wharf" "canada water" 3)
(add-edge! jubilee-line "canada water" "bermondsey" 2)
(add-edge! jubilee-line "bermondsey" "london bridge" 3)
(add-edge! jubilee-line "london bridge" "southwark" 2)
(add-edge! jubilee-line "southwark" "waterloo" 1)
(add-edge! jubilee-line "waterloo" "westminster" 2)
(add-edge! jubilee-line "westminster" "green park" 3)
(add-edge! jubilee-line "green park" "bond street" 2)
(add-edge! jubilee-line "bond street" "baker street" 3)
(add-edge! jubilee-line "baker street" "st johns wood" 3)
(add-edge! jubilee-line "st johns wood" "swiss cottage" 2)
(add-edge! jubilee-line "swiss cottage" "finchley road" 2)
(add-edge! jubilee-line "finchley road" "west hampstead" 1)
(add-edge! jubilee-line "west hampstead" "kilburn" 2)
(add-edge! jubilee-line "kilburn" "willesden green" 2)
(add-edge! jubilee-line "willesden green" "dollis hill" 2)
(add-edge! jubilee-line "dollis hill" "neasden" 2)
(add-edge! jubilee-line "neasden" "wembley park" 3)
(add-edge! jubilee-line "wembley park" "kingsbury" 4)
(add-edge! jubilee-line "kingsbury" "queensbury" 2)
(add-edge! jubilee-line "queensbury" "canons park" 3)
(add-edge! jubilee-line "canons park" "stanmore" 2)

; Metropolitan Line
(define metropolitan-line (make-mutable-graph))
(add-edge! metropolitan-line "chesham" "chalfont & latimer" 8)
(add-edge! metropolitan-line "chalfont & latimer" "amersham" 4)
(add-edge! metropolitan-line "chalfont & latimer" "chorleywood" 4)
(add-edge! metropolitan-line "chorleywood" "rickmanworth" 4)
(add-edge! metropolitan-line "rickmanworth" "moor park" 4)
(add-edge! metropolitan-line "moor park" "croxley" 4)
(add-edge! metropolitan-line "croxley" "watford" 3)
(add-edge! metropolitan-line "moor park" "northwood" 3)
(add-edge! metropolitan-line "northwood" "northwood hills" 2)
(add-edge! metropolitan-line "northwood hills" "pinner" 3)
(add-edge! metropolitan-line "pinner" "north harrow" 2)
(add-edge! metropolitan-line "north harrow" "harrow-on-the-hill" 3)
(add-edge! metropolitan-line "harrow-on-the-hill" "west harrow" 2)
(add-edge! metropolitan-line "west harrow" "rayners lane" 3)
(add-edge! metropolitan-line "rayners lane" "eastcote" 2)
(add-edge! metropolitan-line "eastcote" "ruislip manor" 2)
(add-edge! metropolitan-line "ruislip manor" "ruislip" 2)
(add-edge! metropolitan-line "ruislip" "ickenham" 3)
(add-edge! metropolitan-line "ickenham" "hillingdon" 2)
(add-edge! metropolitan-line "hillingdon" "uxbridge" 3)
(add-edge! metropolitan-line "harrow-on-the-hill" "northwick park" 3)
(add-edge! metropolitan-line "northwick park" "preston road" 2)
(add-edge! metropolitan-line "preston road" "wembley park" 3)
(add-edge! metropolitan-line "wembley park" "finchley road" 7)
(add-edge! metropolitan-line "finchley road" "baker street" 6)
(add-edge! metropolitan-line "baker street" "great portland street" 2)
(add-edge! metropolitan-line "great portland street" "euston square" 2)
(add-edge! metropolitan-line "euston square" "kings cross st pancras" 2)
(add-edge! metropolitan-line "kings cross st pancras" "farringdon" 3)
(add-edge! metropolitan-line "farringdon" "barbican" 2)
(add-edge! metropolitan-line "barbican" "moorgate" 1)
(add-edge! metropolitan-line "moorgate" "liverpool street" 2)
(add-edge! metropolitan-line "liverpool street" "aldgate" 2)

; Piccadilly Line
(define piccadilly-line (make-mutable-graph))
(add-edge! piccadilly-line "uxbridge" "hillingdon" 3)
(add-edge! piccadilly-line "hillingdon" "ickenham" 2)
(add-edge! piccadilly-line "ickenham" "ruislip" 3)
(add-edge! piccadilly-line "ruislip" "ruislip manor" 2)
(add-edge! piccadilly-line "ruislip manor" "eastcote" 2)
(add-edge! piccadilly-line "eastcote" "rayners lane" 2)
(add-edge! piccadilly-line "rayners lane" "south harrow" 3)
(add-edge! piccadilly-line "south harrow" "sudbury hill" 3)
(add-edge! piccadilly-line "sudbury hill" "sudbury town" 2)
(add-edge! piccadilly-line "sudbury town" "alperton" 2)
(add-edge! piccadilly-line "alperton" "park royal" 3)
(add-edge! piccadilly-line "park royal" "north ealing" 2)
(add-edge! piccadilly-line "north ealing" "ealing common" 2)
(add-edge! piccadilly-line "ealing common" "acton town" 2)
(add-edge! piccadilly-line "acton town" "south ealing" 3)
(add-edge! piccadilly-line "south ealing" "northfields" 1)
(add-edge! piccadilly-line "northfields" "boston manor" 2)
(add-edge! piccadilly-line "boston manor" "osterley" 3)
(add-edge! piccadilly-line "osterley" "hounslow east" 2)
(add-edge! piccadilly-line "hounslow east" "hounslow central" 1)
(add-edge! piccadilly-line "hounslow central" "hounslow west" 2)
(add-edge! piccadilly-line "hounslow west" "hatton cross" 4)
(add-edge! piccadilly-line "hatton cross" "heathrow terminal 4" 2)
(add-edge! piccadilly-line "heathrow terminal 4" "heathrow terminals 1, 2, 3" 5)
(add-edge! piccadilly-line "heathrow terminals 1, 2, 3" "hatton cross" 3)
(add-edge! piccadilly-line "acton town" "turnham green" 3)
(add-edge! piccadilly-line "turnham green" "hammersmith" 4)
(add-edge! piccadilly-line "hammersmith" "barons court" 2)
(add-edge! piccadilly-line "barons court" "earls court" 3)
(add-edge! piccadilly-line "earls court" "gloucester road" 2)
(add-edge! piccadilly-line "gloucester road" "south kensington" 1)
(add-edge! piccadilly-line "south kensington" "knightsbridge" 3)
(add-edge! piccadilly-line "knightsbridge" "hyde park corner" 1)
(add-edge! piccadilly-line "hyde park corner" "green park" 2)
(add-edge! piccadilly-line "green park" "piccadilly circus" 1)
(add-edge! piccadilly-line "piccadilly circus" "leicester square" 2)
(add-edge! piccadilly-line "leicester square" "covent garden" 1)
(add-edge! piccadilly-line "covent garden" "holborn" 2)
(add-edge! piccadilly-line "holborn" "russell square" 1)
(add-edge! piccadilly-line "russel square" "kings cross st pancras" 2)
(add-edge! piccadilly-line "kings cross st pancras" "caledonian road" 3)
(add-edge! piccadilly-line "caledonian road" "holloway road" 1)
(add-edge! piccadilly-line "holloway road" "arsenal" 2)
(add-edge! piccadilly-line "arsenal" "finsbury park" 1)
(add-edge! piccadilly-line "finsbury park" "manor house" 2)
(add-edge! piccadilly-line "manor house" "turnpike lane" 3)
(add-edge! piccadilly-line "turnpike lane" "wood green" 2)
(add-edge! piccadilly-line "wood green" "bounds green" 2)
(add-edge! piccadilly-line "bounds green" "arnos grove" 3)
(add-edge! piccadilly-line "arnos grove" "southgate" 3)
(add-edge! piccadilly-line "southgate" "oakwood" 3)
(add-edge! piccadilly-line "oakwood" "cockfosters" 2)

; Victoria Line
(define victoria-line (make-mutable-graph))
(add-edge! victoria-line "walthamstow central" "blackhorse road" 2)
(add-edge! victoria-line "blackhorse road" "tottenham hale" 2)
(add-edge! victoria-line "tottenham hale" "seven sisters" 2)
(add-edge! victoria-line "seven sisters" "finsbury park" 4)
(add-edge! victoria-line "finsbury park" "highbury & islington" 3)
(add-edge! victoria-line "highbury & islington" "kings cross st pancras" 3)
(add-edge! victoria-line "kings cross st pancras" "euston" 2)
(add-edge! victoria-line "euston" "warren street" 1)
(add-edge! victoria-line "warren street" "oxford circus" 2)
(add-edge! victoria-line "oxford circus" "green park" 2)
(add-edge! victoria-line "green park" "victoria" 2)
(add-edge! victoria-line "victoria" "pimlico" 2)
(add-edge! victoria-line "pimlico" "vauxhall" 1)
(add-edge! victoria-line "vauxhall" "stockwell" 3)
(add-edge! victoria-line "stockwell" "brixton" 2)

; Waterloo & City Line
(define waterloo-city-line (make-mutable-graph))
(add-edge! waterloo-city-line "waterloo" "bank" 4)

; London Overground (do it if you dare)

(get-neighbors northern-line "goodge street")           ; Test: check the neighbors of a station with more than one connection, should return (("warren street" 2) ("tottenham court road" 1))
(get-neighbors northern-line "morden")                  ; Test: check the neighbors of a station at the end of the line, should return (("south wimbledon" 3))
(get-neighbors northern-line "high barnet")             ; Test: check the neighbors of a station at the beginning of a line, should return (("totteridge & whetstone" 4))
(get-neighbors northern-line "camden town")             ; Test: check the neighbors of a station with more than two connections, should return (("mornington crescent" 2) ("euston" 3) ("chalk farm" 2) ("kentish town" 2))
(get-weight northern-line "morden" "south wimbledon")   ; Test: check the weight between two staions, should return 3
(get-weight northern-line "south wimbledon" "morden")   ; Test: check if the same works but in reverse, should return 3